import type { Category, Habit } from "./types";

/**
 * Koyu pano uzerinde okunan hat renkleri. Parlakliklari birbirine yakin
 * tutuldu ki bir sutunda alt alta dururken hicbiri one firlamasin.
 */
export const CATEGORIES: { id: Category; label: string; color: string }[] = [
  { id: "zihin", label: "Zihin", color: "#6e9bd1" },
  { id: "beden", label: "Beden", color: "#e0674a" },
  { id: "yaratici", label: "Yaratıcı", color: "#e5a93f" },
  { id: "beceri", label: "Beceri", color: "#8fbe68" },
  { id: "sosyal", label: "Sosyal", color: "#d07ba6" },
  { id: "huzur", label: "Huzur", color: "#5fc0ae" },
];

export const DIFFICULTY_LABEL: Record<number, string> = {
  1: "Kolay başlangıç",
  2: "Orta",
  3: "Meydan okuma",
};

export const HABITS: Habit[] = [
  {
    id: "rubik",
    name: "Rubik Küp Çözmek",
    icon: "cube",
    category: "beceri",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 60,
    description:
      "Katman katman çözüm yöntemiyle küpü çözmeyi öğren. Kas hafızası birkaç günde oturuyor.",
    firstStep:
      "Sadece beyaz artıyı (white cross) yapmayı öğren. Bugünün tek hedefi bu.",
    gear: "Bir adet 3x3 küp",
  },
  {
    id: "kitap",
    name: "Kitap Okumak",
    icon: "book",
    category: "zihin",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 90,
    description:
      "Telefon başka odada, tek iş okumak. Dikkat süresini geri kazanmanın en hızlı yolu.",
    firstStep:
      "Yarım bıraktığın ya da hep merak ettiğin kitabı aç, 20 sayfa oku.",
  },
  {
    id: "gitar",
    name: "Gitar Çalmak",
    icon: "guitar",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 60,
    description:
      "4 akorla çalabileceğin yüzlerce şarkı var. Parmak uçların ilk hafta acır, sonra geçer.",
    firstStep: "Em, G, C, D akorlarını temiz basmaya çalış.",
    gear: "Gitar",
  },
  {
    id: "cizim",
    name: "Çizim / Eskiz",
    icon: "pen",
    category: "yaratici",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 60,
    description:
      "Yetenek değil tekrar işi. Gördüğünü çizmek gözünü hızla eğitiyor.",
    firstStep: "Masandaki bir nesneyi 20 dakika boyunca tek bir çizimde çiz.",
    gear: "Kağıt ve kalem",
  },
  {
    id: "kod",
    name: "Kod Yazmak",
    icon: "terminal",
    category: "beceri",
    difficulty: 3,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Tutorial izlemek değil, küçük de olsa çalışan bir şey bitirmek.",
    firstStep: "Tek dosyalık küçük bir script yaz ve çalıştır.",
  },
  {
    id: "yazma",
    name: "Günlük / Yazı Yazmak",
    icon: "notebook",
    category: "zihin",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 45,
    description:
      "Kafandakileri boşaltmak hem düşünceyi hem yazma kasını güçlendiriyor.",
    firstStep: "Durmadan 15 dakika yaz; silme yok, düzeltme yok.",
  },
  {
    id: "kosu",
    name: "Koşu",
    icon: "run",
    category: "beden",
    difficulty: 2,
    minMinutes: 25,
    maxMinutes: 75,
    description:
      "Yavaş tempo, konuşabildiğin hız. Dayanıklılık haftalar içinde katlanıyor.",
    firstStep: "5 dk yürü, 20 dk çok yavaş koş, 5 dk yürü.",
  },
  {
    id: "guc",
    name: "Kuvvet Antrenmanı",
    icon: "dumbbell",
    category: "beden",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Şınav, squat, barfiks. Ekipman olmadan da ciddi ilerleme mümkün.",
    firstStep: "3 tur: 10 squat, 8 şınav, 30 sn plank.",
  },
  {
    id: "yoga",
    name: "Yoga / Esneme",
    icon: "stretch",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 60,
    description:
      "Masa başı sırtını ve kalçanı geri açar. Uykuyu da belirgin iyileştiriyor.",
    firstStep: "20 dakikalık bir başlangıç akışını takip et.",
  },
  {
    id: "meditasyon",
    name: "Meditasyon",
    icon: "breath",
    category: "huzur",
    difficulty: 1,
    minMinutes: 10,
    maxMinutes: 40,
    description:
      "Dikkatini nefese getirip geri getirmek. Doom scrolling'in tam tersi egzersiz.",
    firstStep: "Zamanlayıcıyı kur, sadece nefesini say: 1'den 10'a, tekrar.",
  },
  {
    id: "dil",
    name: "Yabancı Dil",
    icon: "language",
    category: "zihin",
    difficulty: 2,
    minMinutes: 25,
    maxMinutes: 60,
    description: "Günde 30 dakika, bir yılda konuşulabilir seviye demek.",
    firstStep: "20 yeni kelime seç, sesli tekrar et, cümle içinde kullan.",
  },
  {
    id: "yemek",
    name: "Yemek Pişirmek",
    icon: "chef",
    category: "beceri",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Ömür boyu kullanacağın, parayı ve sağlığı doğrudan etkileyen tek beceri.",
    firstStep: "Daha önce yapmadığın tek tencerelik bir tarif seç ve yap.",
  },
  {
    id: "fotograf",
    name: "Fotoğrafçılık",
    icon: "camera",
    category: "yaratici",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Telefon kamerası fazlasıyla yeter. Mesele ekipman değil, bakmayı öğrenmek.",
    firstStep:
      "Dışarı çık, tek bir tema seç (gölge, kırmızı, doku) ve 30 kare çek.",
  },
  {
    id: "satranc",
    name: "Satranç",
    icon: "chess",
    category: "zihin",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 60,
    description:
      "Taktik bulmacaları, oyun oynamaktan daha hızlı seviye atlatıyor.",
    firstStep: "20 dakika sadece mat bulmacası çöz.",
  },
  {
    id: "piyano",
    name: "Piyano",
    icon: "piano",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 25,
    maxMinutes: 60,
    description: "İki el bağımsızlığı beyni ciddi şekilde çalıştırıyor.",
    firstStep: "Do majör gamını iki elle, metronomla yavaş çalış.",
    gear: "Piyano ya da klavye",
  },
  {
    id: "yuzme",
    name: "Yüzme",
    icon: "swim",
    category: "beden",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 90,
    description: "Eklem dostu, tüm vücudu çalıştıran tek kardiyo.",
    firstStep: "Teknik düşünmeden 20 dakika rahat tempoda yüz.",
  },
  {
    id: "yuruyus",
    name: "Uzun Yürüyüş",
    icon: "hike",
    category: "huzur",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 120,
    description:
      "Kulaklıksız yürüyüş, tıkanan düşünceleri açan en ucuz yöntem.",
    firstStep: "Telefonu cebe koy, 45 dakika hiç durmadan yürü.",
  },
  {
    id: "origami",
    name: "Origami",
    icon: "origami",
    category: "beceri",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 45,
    description: "Ucuz, sessiz ve tamamen elle yapılan iş. Sabır egzersizi gibi.",
    firstStep: "Klasik turnayı katlamayı öğren.",
    gear: "Birkaç kare kağıt",
  },
  {
    id: "muzik-yapim",
    name: "Müzik Prodüksiyon",
    icon: "mixer",
    category: "yaratici",
    difficulty: 3,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "8 bar loop bile bitirmek, tüketmekten çok farklı hissettiriyor.",
    firstStep: "Bir DAW aç ve 8 barlık tek bir loop bitir.",
  },
  {
    id: "bahce",
    name: "Bitki / Bahçe",
    icon: "plant",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 60,
    description: "Yavaş geri bildirim veren, ekrandan tamamen uzak bir uğraş.",
    firstStep: "Bir saksı hazırla, tohum ek ya da bitkilerini elden geçir.",
  },
  {
    id: "kaligrafi",
    name: "Kaligrafi",
    icon: "calligraphy",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 45,
    description: "El yazını da doğrudan düzeltiyor, sonucu hemen görünüyor.",
    firstStep: "Tek bir harfi bir sayfa boyunca tekrar et.",
    gear: "Uçlu kalem",
  },
  {
    id: "sohbet",
    name: "Gerçek Sohbet",
    icon: "coffee",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 120,
    description: "Mesajlaşmak değil: telefonla ara ya da yüz yüze buluş.",
    firstStep: "Uzun süredir konuşmadığın birini ara, 30 dakika konuş.",
  },
  {
    id: "gonullu",
    name: "Gönüllülük",
    icon: "handshake",
    category: "sosyal",
    difficulty: 2,
    minMinutes: 60,
    maxMinutes: 120,
    description: "Sokak hayvanları, mahalle temizliği, komşuya yardım.",
    firstStep: "Mahallende bugün yapabileceğin tek somut iş bul ve yap.",
  },
  {
    id: "tamir",
    name: "Tamir / El İşi",
    icon: "wrench",
    category: "beceri",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Bozuk eşyayı atmak yerine sökmek, hem öğretici hem tatmin edici.",
    firstStep: "Evdeki bozuk bir şeyi seç, söküp neyin bozulduğunu bul.",
  },

  // ── Zihin ─────────────────────────────────────────────────────────────
  {
    id: "hafiza-sarayi",
    name: "Hafıza Sarayı",
    icon: "memory",
    category: "zihin",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Bilgiyi tanıdık bir mekana yerleştirip zihinde yürüyerek hatırlamak.",
    firstStep:
      "Evini zihninde gez, 10 durak seç, alışveriş listesini o duraklara yerleştir.",
  },
  {
    id: "zihinden-hesap",
    name: "Zihinden Hesap",
    icon: "calculator",
    category: "zihin",
    difficulty: 2,
    minMinutes: 15,
    maxMinutes: 40,
    description:
      "Kalem kağıt yok. Çarpma kısayolları hesap makinesi refleksini kırıyor.",
    firstStep: "İki basamaklı 20 çarpım çöz; hepsini sadece kafadan yap.",
  },
  {
    id: "sudoku",
    name: "Sudoku",
    icon: "sudoku",
    category: "zihin",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 45,
    description:
      "Tek kuralla ilerleyen saf mantık. Dikkati toparlamak için kısa ve net.",
    firstStep:
      "Kolay seviye bir bulmacayı baştan sona, hiç tahmin yapmadan bitir.",
  },
  {
    id: "kare-bulmaca",
    name: "Kare Bulmaca",
    icon: "crossword",
    category: "zihin",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description: "Kelime dağarcığını ve ipucu okumayı aynı anda çalıştırıyor.",
    firstStep: "Bir bulmacayı aç, önce üç harfli bütün kelimeleri doldur.",
    gear: "Bulmaca dergisi",
  },
  {
    id: "go",
    name: "Go Oyunu",
    icon: "go",
    category: "zihin",
    difficulty: 3,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Satrançtan basit kurallı ama daha derin oyun. 9x9 tahtada bir saatte öğreniliyor.",
    firstStep: "9x9 tahtada tek bir oyun oyna; tek amacın alan çevirmek olsun.",
  },
  {
    id: "bric",
    name: "Briç",
    icon: "cards",
    category: "zihin",
    difficulty: 3,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Eşinle sinyal dili kurmayı gerektiren tek kart oyunu; hafıza da şart.",
    firstStep:
      "Dört kişi toplan, sadece temel deklarasyonlarla iki parti oyna.",
    gear: "İskambil destesi",
  },
  {
    id: "kor-daktilo",
    name: "Kör Daktilo",
    icon: "keyboard",
    category: "zihin",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 40,
    description:
      "Klavyeye bakmayı bırakmak yazma hızını kalıcı olarak katlıyor.",
    firstStep:
      "Ellerini asıl sıraya koy, sadece ASDF-JKL harfleriyle 15 dakika çalış.",
  },
  {
    id: "astronomi",
    name: "Amatör Astronomi",
    icon: "telescope",
    category: "zihin",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Şehirde bile Jüpiter'in uyduları ve Ay kraterleri dürbünle görünüyor.",
    firstStep:
      "Hava açıksa Ay'ı bul, kraterlerin gölge çizgisini 30 dakika izle.",
    gear: "Dürbün ya da teleskop",
  },
  {
    id: "kus-gozlemi",
    name: "Kuş Gözlemi",
    icon: "binoculars",
    category: "zihin",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Aynı parkta onlarca tür var; ayırt etmek dikkati ve sabrı çalıştırıyor.",
    firstStep: "Parka git, gördüğün her kuşu defterine çiz ve sesini not et.",
    gear: "Dürbün",
  },
  {
    id: "felsefe",
    name: "Felsefe Metni",
    icon: "scroll",
    category: "zihin",
    difficulty: 3,
    minMinutes: 30,
    maxMinutes: 60,
    description: "Zor metni yavaş okumak, hızlı tüketmenin tam tersi bir kas.",
    firstStep: "Kısa bir diyalog seç, 10 sayfayı kenarına not alarak oku.",
  },
  {
    id: "kitap-ozeti",
    name: "Kitap Özeti",
    icon: "summary",
    category: "zihin",
    difficulty: 2,
    minMinutes: 25,
    maxMinutes: 60,
    description:
      "Okuduğunu kendi cümlelerinle yazmak akılda kalma oranını belirgin artırıyor.",
    firstStep: "Son bitirdiğin kitabı tek sayfada, kitaba bakmadan özetle.",
  },
  {
    id: "anlatarak",
    name: "Anlatarak Öğrenmek",
    icon: "teach",
    category: "zihin",
    difficulty: 2,
    minMinutes: 25,
    maxMinutes: 60,
    description:
      "Bildiğini boş odaya anlatmak, bilmediğin yeri anında ortaya çıkarıyor.",
    firstStep: "Bir konu seç, kimse yokken tahtaya yazarak 20 dakika anlat.",
  },
  {
    id: "zihin-haritasi",
    name: "Zihin Haritası",
    icon: "mindmap",
    category: "zihin",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Kafadaki dağınık konuyu tek sayfada dallandırmak kararı hızlandırıyor.",
    firstStep: "Ortaya tek bir soru yaz, etrafına en az 20 dal çıkar.",
  },
  {
    id: "tarih-okuma",
    name: "Tarih Okuması",
    icon: "history",
    category: "zihin",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Bugünün haberi yerine iki yüz yıl önceki aynı tartışmayı okumak.",
    firstStep:
      "Yaşadığın şehrin tarihini anlatan bir bölüm oku ve kronoloji çıkar.",
  },
  {
    id: "atlas",
    name: "Atlas Okuma",
    icon: "map",
    category: "zihin",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Haritaya bakmak, ülke ezberlemekten farklı bir mekan sezgisi veriyor.",
    firstStep:
      "Bir kıta seç; ülkeleri ve başkentlerini haritayı kapatarak tekrar bul.",
    gear: "Atlas ya da harita",
  },
  {
    id: "mantik-bulmaca",
    name: "Mantık Bulmacası",
    icon: "logic",
    category: "zihin",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Tablo tutarak çözülen çıkarım egzersizleri; tahmin işe yaramıyor.",
    firstStep:
      "Izgaralı bir bulmaca al, her ipucunu tabloya işaretleyerek çöz.",
  },
  {
    id: "yapboz",
    name: "Yapboz",
    icon: "jigsaw",
    category: "zihin",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 120,
    description:
      "Beş yüz parça ve sessiz bir oda. Sonu belli, elle yapılan tatmin edici iş.",
    firstStep: "Kenar parçalarını ayır ve çerçeveyi tamamla.",
    gear: "Yapboz",
  },
  {
    id: "siir-ezber",
    name: "Şiir Ezberlemek",
    icon: "recite",
    category: "zihin",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 40,
    description:
      "Ezber kötü bir alışkanlık değil; ritmi olan metin akılda kolay kalıyor.",
    firstStep: "Kısa bir şiir seç, iki kıtasını sesli tekrarla ezberle.",
  },
  {
    id: "matematik",
    name: "Matematik Problemi",
    icon: "sigma",
    category: "zihin",
    difficulty: 3,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Çözümünü bilmediğin tek problemle boğuşmak, video izlemekten bambaşka.",
    firstStep: "Bir olimpiyat sorusu seç, çözemesen de 30 dakika üstünde kal.",
  },
  {
    id: "gazete",
    name: "Gazete Okuma",
    icon: "newspaper",
    category: "zihin",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Akış yerine sayfa: baştan sona okunan, nerede bittiği belli olan haber.",
    firstStep: "Basılı bir gazete al, telefon başka odada, baştan sona oku.",
    gear: "Basılı gazete",
  },
  {
    id: "dama",
    name: "Dama",
    icon: "checkers",
    category: "zihin",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 45,
    description:
      "Yarım saatte öğrenilen, taktiği yine derin olan klasik tahta oyunu.",
    firstStep:
      "Tek parti oyna; her hamlede rakibin zorunlu alışını önceden hesapla.",
  },
  {
    id: "hizli-not",
    name: "Hızlı Not Alma",
    icon: "shorthand",
    category: "zihin",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description: "Konuşulanı yakalamak için kendi kısaltma sistemini kurmak.",
    firstStep:
      "En sık yazdığın 30 kelime için birer kısaltma belirle ve deneyerek yaz.",
  },

  // ── Beden ─────────────────────────────────────────────────────────────
  {
    id: "bisiklet",
    name: "Bisiklet",
    icon: "bike",
    category: "beden",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 120,
    description:
      "Eklemi yormayan kardiyo; şehri de bambaşka bir hızda görüyorsun.",
    firstStep: "Rota planla, 30 dakika düz zeminde sabit tempoda pedal çevir.",
    gear: "Bisiklet",
  },
  {
    id: "ip-atlama",
    name: "İp Atlama",
    icon: "jumprope",
    category: "beden",
    difficulty: 2,
    minMinutes: 15,
    maxMinutes: 40,
    description:
      "Bir metrekare yer yeter. Koordinasyonu ve nabzı aynı anda çalıştırıyor.",
    firstStep: "30 saniye atla, 30 saniye dinlen; bunu 10 tur tekrarla.",
    gear: "Atlama ipi",
  },
  {
    id: "kalistenik",
    name: "Kalistenik",
    icon: "calisthenics",
    category: "beden",
    difficulty: 3,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Vücut ağırlığıyla barfiks ve dips yolu. Ekipman değil teknik gerekiyor.",
    firstStep:
      "Negatif barfiks çalış: 5 tekrar, her birinde 5 saniyede aşağı in.",
  },
  {
    id: "kurek",
    name: "Kürek Çekmek",
    icon: "rowing",
    category: "beden",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 60,
    description:
      "Tek harekette bacak, sırt ve kol; kısa sürede en çok iş çıkaran kardiyo.",
    firstStep: "2000 metreyi süre tutmadan, sadece tekniğe bakarak çek.",
    gear: "Kürek makinesi",
  },
  {
    id: "tirmanis",
    name: "Boulder Tırmanış",
    icon: "climb",
    category: "beden",
    difficulty: 3,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Problem çözerek yapılan spor; kavrama gücü ve rota okuma birlikte gelişiyor.",
    firstStep: "Salonda en kolay rotayı seç ve aynı rotayı üç kez tırman.",
    gear: "Tırmanış ayakkabısı",
  },
  {
    id: "dovus",
    name: "Dövüş Sanatı",
    icon: "martial",
    category: "beden",
    difficulty: 3,
    minMinutes: 45,
    maxMinutes: 90,
    description:
      "Boks, muay thai ya da jiu jitsu: teknik, kondisyon ve soğukkanlılık bir arada.",
    firstStep:
      "Temel duruşu ve tek bir vuruşu aynanın karşısında 20 dakika tekrar et.",
  },
  {
    id: "masa-tenisi",
    name: "Masa Tenisi",
    icon: "pingpong",
    category: "beden",
    difficulty: 1,
    minMinutes: 25,
    maxMinutes: 60,
    description:
      "Refleks ve göz-el uyumu; kapalı alanda yıl boyunca oynanıyor.",
    firstStep: "Duvara karşı 20 dakika sadece forehand vur.",
    gear: "Raket",
  },
  {
    id: "tenis",
    name: "Tenis",
    icon: "ball",
    category: "beden",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 90,
    description:
      "Ayak işi kardiyo, kol işi teknik. Tek maç bir saatlik antrenman ediyor.",
    firstStep:
      "Duvara karşı 20 dakika servis at; hedefe düşen sayısını not et.",
    gear: "Raket",
  },
  {
    id: "basketbol",
    name: "Basketbol",
    icon: "hoop",
    category: "beden",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 90,
    description:
      "Tek başına da çalışılır: şut ve top sürme saatlerce tekrar isteyen işler.",
    firstStep: "Serbest atış çizgisinden 50 şut at, isabet sayını yaz.",
    gear: "Top",
  },
  {
    id: "hali-saha",
    name: "Halı Saha Maçı",
    icon: "pitch",
    category: "beden",
    difficulty: 2,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Haftada bir saat koşu, üstüne sekiz kişilik gerçek bir sosyal ortam.",
    firstStep: "Sekiz kişi topla, saat ayır ve maçı sonuna kadar oyna.",
  },
  {
    id: "paten",
    name: "Paten / Kaykay",
    icon: "skate",
    category: "beden",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 75,
    description: "Denge ve düşme cesareti; öğrenme eğrisi ilk hafta çok hızlı.",
    firstStep: "Düz zeminde sadece kaymayı ve durmayı 30 dakika çalış.",
    gear: "Paten ya da kaykay",
  },
  {
    id: "dans",
    name: "Dans Etmek",
    icon: "dance",
    category: "beden",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Kardiyoyu spor gibi hissettirmeyen tek yol; ritim de kas hafızası işi.",
    firstStep: "Tek bir şarkının adımlarını yavaş tempoda 30 dakika tekrarla.",
  },
  {
    id: "sprint",
    name: "Sprint / İnterval",
    icon: "sprint",
    category: "beden",
    difficulty: 3,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Kısa ve sert. Yirmi dakikada uzun koşu kadar kondisyon yüklüyor.",
    firstStep:
      "10 dakika ısın, sonra 6 kez 30 saniye hızlı - 90 saniye yürüyüş yap.",
  },
  {
    id: "merdiven",
    name: "Merdiven Çıkmak",
    icon: "stairs",
    category: "beden",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Apartman boşluğu bedava bir kardiyo aleti; bacakları da hızla güçlendiriyor.",
    firstStep: "Beş kat merdiveni yürüyerek çık, asansörle in; bunu 6 tur yap.",
  },
  {
    id: "mobility",
    name: "Mobility Çalışması",
    icon: "mobility",
    category: "beden",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 45,
    description:
      "Esnemekten farklı: eklemin kendi gücüyle gidebildiği alanı büyütmek.",
    firstStep:
      "Kalça, omuz ve ayak bileği için üçer hareket seç, yavaşça çalış.",
  },
  {
    id: "trekking",
    name: "Dağ Yürüyüşü",
    icon: "trek",
    category: "beden",
    difficulty: 2,
    minMinutes: 60,
    maxMinutes: 120,
    description: "Eğimli zemin, yürüyüşü tamamen başka bir spora çeviriyor.",
    firstStep: "İşaretli kısa bir parkur seç, su al ve baştan sona yürü.",
    gear: "Bot ve su",
  },
  {
    id: "oryantiring",
    name: "Oryantiring",
    icon: "compass",
    category: "beden",
    difficulty: 3,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Koşuyla harita okumayı birleştiren spor; yön bulma becerisi de kalıcı.",
    firstStep: "Parkta 5 nokta belirle, haritadan bakarak sırayla hepsini bul.",
    gear: "Pusula ve harita",
  },
  {
    id: "frizbi",
    name: "Frizbi",
    icon: "frisbee",
    category: "beden",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 60,
    description:
      "İki kişi ve boş bir alan yeterli; omuz ve koşu aynı anda çalışıyor.",
    firstStep:
      "Karşılıklı geçin, 30 dakika boyunca hiç yere düşürmemeye çalış.",
    gear: "Frizbi",
  },
  {
    id: "kettlebell",
    name: "Kettlebell",
    icon: "kettlebell",
    category: "beden",
    difficulty: 3,
    minMinutes: 25,
    maxMinutes: 60,
    description:
      "Tek bir aletle salınım ve kaldırış; kavrama gücünü de hızla artırıyor.",
    firstStep:
      "Sadece salınım (swing) çalış: 10 tekrar, 10 tur, aralarda dinlen.",
    gear: "Kettlebell",
  },
  {
    id: "denge",
    name: "Denge / Slackline",
    icon: "balance",
    category: "beden",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Görünmez kaslar: ayak bileği ve gövde stabilizasyonu doğrudan çalışıyor.",
    firstStep:
      "Tek ayak üstünde gözler kapalı 30 saniye dur, iki tarafta 10 tur yap.",
  },

  // ── Yaratıcı ─────────────────────────────────────────────────────────────
  {
    id: "suluboya",
    name: "Suluboya",
    icon: "watercolor",
    category: "yaratici",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Ucuz, sessiz ve hızlı kuruyan boya. Hata yapmayı öğretmesi en büyük faydası.",
    firstStep: "Tek renkle üç ton çıkar: açık, orta, koyu. Sadece bunu çalış.",
    gear: "Suluboya seti",
  },
  {
    id: "akrilik",
    name: "Akrilik Boya",
    icon: "acrylic",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Üst üste boyanabildiği için geri dönüşü olan tek başlangıç tekniği.",
    firstStep: "Küçük bir tuvale tek nesne çiz ve arka planı düz renkle kapat.",
    gear: "Akrilik boya ve tuval",
  },
  {
    id: "seramik",
    name: "Seramik / Çömlek",
    icon: "ceramic",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Elin çamurla çalışması, ekran işinden en uzak duyusal deneyim.",
    firstStep:
      "Bir top kili elde yuvarlayıp sıkıştırma yöntemiyle küçük bir kase yap.",
    gear: "Kil",
  },
  {
    id: "linol",
    name: "Linol Baskı",
    icon: "print",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 90,
    description: "Oyup basmak; tek kalıptan onlarca baskı çıkıyor.",
    firstStep: "Basit bir şekli linole oy ve beş kağıda bas.",
    gear: "Linol ve oyma kalemi",
  },
  {
    id: "kolaj",
    name: "Kolaj",
    icon: "collage",
    category: "yaratici",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 60,
    description: "Çizim yeteneği gerekmiyor; mesele kesip yeniden kurmak.",
    firstStep: "Eski dergilerden 30 parça kes, tek sayfada bir sahne kur.",
    gear: "Dergi ve makas",
  },
  {
    id: "zine",
    name: "Zine Yapmak",
    icon: "zine",
    category: "yaratici",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Tek A4'ü katlayıp sekiz sayfalık dergi yapmak; baskı ya da izin gerekmiyor.",
    firstStep:
      "Bir A4'ü sekize katla, tek konuda sekiz sayfalık mini dergi doldur.",
  },
  {
    id: "cizgi-roman",
    name: "Çizgi Roman",
    icon: "comic",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Çizimle anlatıyı birleştirmek; kare düzeni tek başına bir dil.",
    firstStep: "Tek sayfaya 6 kare çiz ve tek bir olayı baştan sona anlat.",
  },
  {
    id: "karakter",
    name: "Karakter Tasarımı",
    icon: "character",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Aynı yüzü onlarca kez çizmek, çizim kasını en hızlı oturtan egzersiz.",
    firstStep: "Tek bir karakteri 10 farklı ifadeyle çiz.",
  },
  {
    id: "tipografi",
    name: "Harf Çizimi",
    icon: "lettering",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 15,
    maxMinutes: 60,
    description:
      "Yazı tipi çizmek, gözü boşluk ve orantı konusunda hızla eğitiyor.",
    firstStep: "Tek bir kelimeyi üç farklı harf stiliyle, kalemle çiz.",
  },
  {
    id: "dikis",
    name: "Dikiş Dikmek",
    icon: "sewing",
    category: "yaratici",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 90,
    description:
      "Sökülen düğmeden pantolon boyuna: hayatı doğrudan kolaylaştıran el işi.",
    firstStep: "Bir düğme dik, sonra sökülmüş bir dikişi elde onar.",
    gear: "İğne ve iplik",
  },
  {
    id: "orgu",
    name: "Örgü / Tığ İşi",
    icon: "knitting",
    category: "yaratici",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Tekrarlayan el hareketi; hem sakinleştiriyor hem sonunda giyilir bir şey çıkıyor.",
    firstStep: "Zincir başlat ve 20 sıra tek tip ilmek ör.",
    gear: "Yumak ve tığ",
  },
  {
    id: "nakis",
    name: "Nakış",
    icon: "embroidery",
    category: "yaratici",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Kasnağa gerilmiş bez üstünde iğneyle çizmek. Malzeme neredeyse bedava.",
    firstStep: "Kasnağa bez ger, tek bir şekli düz nakış iğnesiyle doldur.",
    gear: "Nakış kasnağı",
  },
  {
    id: "makrome",
    name: "Makrome",
    icon: "macrame",
    category: "yaratici",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 75,
    description: "Sadece düğümlerden oluşan dokuma; üç düğüm öğrenmek yetiyor.",
    firstStep: "Kare düğümü öğren ve 20 santim uzunlukta bir şerit ör.",
    gear: "Makrome ipi",
  },
  {
    id: "taki",
    name: "Takı Yapımı",
    icon: "jewelry",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Küçük parçalarla çalışmak el hassasiyetini ciddi şekilde geliştiriyor.",
    firstStep:
      "Tel ve boncukla tek bir bileklik yap, kapamasını da kendin kur.",
    gear: "Boncuk ve tel",
  },
  {
    id: "ahsap-oyma",
    name: "Ahşap Oyma",
    icon: "carving",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Bir parça ıhlamur ve tek çakı; talaş çıkardıkça iş ortaya çıkıyor.",
    firstStep: "Yumuşak bir tahta parçasından kaşık kabası çıkar.",
    gear: "Yumuşak tahta ve oyma bıçağı",
  },
  {
    id: "maket",
    name: "Maket / Diorama",
    icon: "model",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Yetenek değil talimat takibi ve sabır işi; sonucu elle tutulur.",
    firstStep: "Küçük bir maket kutusu al ve tek oturuşta iskeletini bitir.",
    gear: "Maket seti",
  },
  {
    id: "stop-motion",
    name: "Stop Motion",
    icon: "stopmotion",
    category: "yaratici",
    difficulty: 3,
    minMinutes: 60,
    maxMinutes: 120,
    description: "Kare kare çekim; 5 saniyelik plan bile bir saatlik ciddi iş.",
    firstStep: "Bir nesneyi 60 kare boyunca azar azar oynatıp fotoğrafla.",
  },
  {
    id: "kisa-film",
    name: "Kısa Film Çekmek",
    icon: "shortfilm",
    category: "yaratici",
    difficulty: 3,
    minMinutes: 60,
    maxMinutes: 120,
    description: "Telefon kamerası yeter; asıl iş plan çıkarmak ve kurgulamak.",
    firstStep: "Tek mekanda geçen 60 saniyelik bir sahne çek ve kurgula.",
  },
  {
    id: "siir",
    name: "Şiir Yazmak",
    icon: "poem",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 60,
    description: "Az kelimeyle çok şey söylemeye zorlayan tek yazı biçimi.",
    firstStep: "Tek bir nesneyi anlatan 12 satırlık şiir yaz, sıfat kullanma.",
  },
  {
    id: "oyku",
    name: "Kısa Öykü",
    icon: "story",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Bir sahne, iki karakter, tek çatışma. Roman yazmaktan çok daha öğretici.",
    firstStep: "Tek sahnede geçen 500 kelimelik bir öykü yaz ve bitir.",
  },
  {
    id: "senaryo",
    name: "Senaryo Yazmak",
    icon: "screenplay",
    category: "yaratici",
    difficulty: 3,
    minMinutes: 45,
    maxMinutes: 120,
    description: "Sadece görünen ve duyulanı yazmak; iç sesi anlatmak yasak.",
    firstStep: "İki kişilik tek sahne yaz; hiçbir duyguyu açıkça söyleme.",
  },
  {
    id: "sarki-sozu",
    name: "Şarkı Sözü",
    icon: "lyrics",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 25,
    maxMinutes: 60,
    description:
      "Ölçü ve kafiye kısıtı, düz yazının asla vermediği bir disiplin veriyor.",
    firstStep: "Bildiğin bir melodiye yeni bir kıta söz yaz.",
  },
  {
    id: "bateri",
    name: "Bateri / Davul",
    icon: "drum",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 25,
    maxMinutes: 60,
    description:
      "Ritim duygusu doğuştan değil; metronomla iki haftada oturuyor.",
    firstStep:
      "Metronomu 60'a kur ve tek bir temel ritmi 20 dakika bozmadan çal.",
    gear: "Davul ya da pad",
  },
  {
    id: "ukulele",
    name: "Ukulele",
    icon: "ukulele",
    category: "yaratici",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 60,
    description:
      "Dört tel, yumuşak naylon: gitardan çok daha hızlı ilk şarkıya götürüyor.",
    firstStep: "C, Am, F, G akorlarını bas ve aralarında geçiş yap.",
    gear: "Ukulele",
  },
  {
    id: "keman",
    name: "Keman",
    icon: "violin",
    category: "yaratici",
    difficulty: 3,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Perde yok, sesi kendin buluyorsun. İlk hafta zor, sonrası bağımlılık.",
    firstStep: "Yayı boş tellerde düz ve temiz çekmeyi 30 dakika çalış.",
    gear: "Keman",
  },
  {
    id: "sanvokal",
    name: "Vokal / Şan",
    icon: "vocal",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 60,
    description:
      "Ses de bir kas; nefes desteği ve aralık çalışmasıyla belirgin açılıyor.",
    firstStep:
      "Nefes egzersizi yap, sonra tek bir gamı alçaktan yükseğe söyle.",
  },
  {
    id: "dogaclama",
    name: "Doğaçlama Tiyatro",
    icon: "improv",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 90,
    description:
      "Hazırlıksız sahne almak, sosyal cesareti ve hızlı düşünmeyi birlikte açıyor.",
    firstStep: "Bir arkadaşınla 'evet, ve' kuralıyla 20 dakika sahne kur.",
  },
  {
    id: "seslendirme",
    name: "Seslendirme",
    icon: "voiceover",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 25,
    maxMinutes: 60,
    description:
      "Metni sesle canlandırmak; vurgu ve tempo tamamen çalışılabilir şeyler.",
    firstStep: "Bir sayfa metni üç farklı tonda okuyup kaydet, sonra dinle.",
  },
  {
    id: "ebru",
    name: "Ebru",
    icon: "ebru",
    category: "yaratici",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Su üstüne boya: sonucu tam kontrol edemediğin için ele geçme hissi veriyor.",
    firstStep: "Tekneye boya damlat, tarakla tek bir klasik desen çıkar.",
    gear: "Ebru teknesi ve boya",
  },
  {
    id: "bonsai",
    name: "Bonsai",
    icon: "bonsai",
    category: "yaratici",
    difficulty: 3,
    minMinutes: 30,
    maxMinutes: 60,
    description:
      "Yıllara yayılan tek uğraş; her budama kararının sonucu aylar sonra görünüyor.",
    firstStep:
      "Ağacın ölü dallarını temizle ve tek bir dalı şekillendirmeye başla.",
    gear: "Bonsai ve makas",
  },

  // ── Beceri ─────────────────────────────────────────────────────────────
  {
    id: "marangozluk",
    name: "Marangozluk",
    icon: "carpentry",
    category: "beceri",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Ölçmek, kesmek, birleştirmek. Evdeki her eşyaya bakışını değiştiriyor.",
    firstStep: "Tahta parçalarından tek bir küçük raf yap ve duvara as.",
    gear: "Testere ve zımpara",
  },
  {
    id: "lehim",
    name: "Lehim / Elektronik",
    icon: "solder",
    category: "beceri",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 90,
    description: "Bozuk kabloyu ve devreyi kendin onarmak; malzeme çok ucuz.",
    firstStep: "Delikli plakete bir LED ve direnç lehimleyip pille yak.",
    gear: "Havya ve lehim",
  },
  {
    id: "arduino",
    name: "Arduino Devresi",
    icon: "arduino",
    category: "beceri",
    difficulty: 3,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Yazdığın kodun gerçek dünyada bir şeyi hareket ettirmesi bambaşka.",
    firstStep: "LED'i saniyede bir yanıp söndüren devreyi kur ve kodunu yaz.",
    gear: "Arduino seti",
  },
  {
    id: "uc-boyut",
    name: "3B Baskı",
    icon: "printer3d",
    category: "beceri",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Modelden nesneye giden yol; ölçü hatalarını elinde tutarak öğreniyorsun.",
    firstStep: "Basit bir parçayı modelle ve ilk baskıyı al.",
    gear: "3B yazıcı",
  },
  {
    id: "pc-toplama",
    name: "PC Toplamak",
    icon: "pcbuild",
    category: "beceri",
    difficulty: 2,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Kasanın içi karmaşık değil; bir kere yapan bir daha servise gitmiyor.",
    firstStep: "Eski bir kasayı tamamen sök, temizle ve baştan kur.",
  },
  {
    id: "bisiklet-bakim",
    name: "Bisiklet Bakımı",
    icon: "bikefix",
    category: "beceri",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Vites ayarı ve lastik yaması, her sürüşü doğrudan iyileştiriyor.",
    firstStep: "Zinciri temizle, yağla ve arka vites ayarını düzelt.",
    gear: "Alyan takımı",
  },
  {
    id: "dugum",
    name: "Düğüm Bağlamak",
    icon: "knots",
    category: "beceri",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Altı düğüm ömür boyu yetiyor; kamp, taşıma ve tamir işlerinde sürekli çıkıyor.",
    firstStep:
      "Kazık bağı ve sekiz düğümünü gözün kapalı bağlayana kadar tekrarla.",
    gear: "Bir parça halat",
  },
  {
    id: "kamp",
    name: "Kamp Kurmak",
    icon: "camp",
    category: "beceri",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Çadır, yer seçimi ve rüzgar yönü: hepsi tekrar ettikçe otomatikleşiyor.",
    firstStep: "Çadırı bahçede ya da salonda kurup söküp tekrar kur.",
    gear: "Çadır",
  },
  {
    id: "ates",
    name: "Ateş Yakmak",
    icon: "fire",
    category: "beceri",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 60,
    description:
      "Çakmaksız ateş; sabır ve malzeme bilgisi gerektiren temel bir beceri.",
    firstStep: "Kuru çıra hazırla ve tek kibritle ateşi tutuşturup sürdür.",
  },
  {
    id: "ilk-yardim",
    name: "İlk Yardım",
    icon: "firstaid",
    category: "beceri",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 60,
    description:
      "Bir kez öğrenilen ve umulmadık bir günde hayat kurtaran bilgi.",
    firstStep:
      "Temel yaşam desteği adımlarını ezberle ve yastıkta bası tekrarını yap.",
  },
  {
    id: "barista",
    name: "Barista / Espresso",
    icon: "espresso",
    category: "beceri",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Öğütme, doz ve süre: üç değişkenli somut bir kalibrasyon işi.",
    firstStep:
      "Aynı çekirdekle üç farklı öğütme denemesi yap ve tatlarını not et.",
    gear: "Öğütücü",
  },
  {
    id: "kokteyl",
    name: "Kokteyl Yapımı",
    icon: "cocktail",
    category: "beceri",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Oran ve denge işi; alkolsüz varyasyonları da aynı tekniği öğretiyor.",
    firstStep:
      "Tek bir klasik tarifi ölçerek üç kez yap, oranı değiştirip karşılaştır.",
  },
  {
    id: "ekmek",
    name: "Ekşi Maya Ekmek",
    icon: "bread",
    category: "beceri",
    difficulty: 2,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Yaşayan bir maya beslemek; sonucu her hafta elle ölçülebiliyor.",
    firstStep: "Un ve suyu karıştırıp maya başlat, 12 saat sonra kontrol et.",
  },
  {
    id: "fermente",
    name: "Turşu / Fermente",
    icon: "ferment",
    category: "beceri",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 60,
    description: "Tuz, su ve zaman. Mutfakta en az emekle en görünür sonuç.",
    firstStep: "Bir kavanoz salatalık turşusu kur ve tarihini üstüne yaz.",
    gear: "Cam kavanoz",
  },
  {
    id: "balik-tutma",
    name: "Balık Tutmak",
    icon: "fishing",
    category: "beceri",
    difficulty: 1,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Beklemeyi tolere etmeyi öğreten uğraş; iğne bağlamak da ayrı bir beceri.",
    firstStep: "Oltayı kur, iğneyi kendin bağla ve iki saat sahilde dene.",
    gear: "Olta takımı",
  },
  {
    id: "mantar",
    name: "Mantar Toplamak",
    icon: "foraging",
    category: "beceri",
    difficulty: 3,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Bilmediğini yememek şartıyla: ormanı okumayı öğreten ciddi bir uğraş.",
    firstStep:
      "Tek bir türü kitaptan çalış, ormanda sadece onu ara ve fotoğrafla.",
    gear: "Tür kitabı",
  },
  {
    id: "bicak-bileme",
    name: "Bıçak Bilemek",
    icon: "sharpen",
    category: "beceri",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Kör bıçak mutfakta en büyük tehlike; bileme yarım saatte öğreniliyor.",
    firstStep:
      "Bileği taşını ıslat ve tek bıçağı sabit açıyla kağıt kesene kadar bile.",
    gear: "Bileği taşı",
  },
  {
    id: "jonglorluk",
    name: "Jonglörlük",
    icon: "juggle",
    category: "beceri",
    difficulty: 2,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Üç top kaskadı iki haftada oturuyor; el-göz uyumu için saf egzersiz.",
    firstStep: "Tek topla atış-yakalama yap, sonra ikinci topu ekle.",
    gear: "Üç top",
  },
  {
    id: "kart-hilesi",
    name: "Kart Hilesi",
    icon: "cardtrick",
    category: "beceri",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 60,
    description:
      "Parmak becerisi ve yönlendirme; seyirci karşısında test etmesi de kolay.",
    firstStep: "Tek bir kart bulma numarası öğren ve aynada 20 kez tekrarla.",
    gear: "İskambil destesi",
  },
  {
    id: "dikis-makinesi",
    name: "Dikiş Makinesi",
    icon: "machine",
    category: "beceri",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Elde saatler süren iş makinede dakikalara iniyor; kıyafet tadilatı da açılıyor.",
    firstStep:
      "Artık bezde düz dikiş ve dönüş çalış, iplik gerginliğini ayarla.",
    gear: "Dikiş makinesi",
  },
  {
    id: "deri",
    name: "Deri İşçiliği",
    icon: "leather",
    category: "beceri",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Kesip dikilen deri yıllarca kullanılıyor; alet listesi de kısa.",
    firstStep: "Bir parça deriden kartlık kes ve el dikişiyle birleştir.",
    gear: "Deri ve tığ",
  },
  {
    id: "saat-tamiri",
    name: "Saat Tamiri",
    icon: "watchfix",
    category: "beceri",
    difficulty: 3,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Milimetrik parçalarla çalışmak; el titremesini ve sabrı doğrudan test ediyor.",
    firstStep: "Ucuz mekanik bir saati aç, kurma mekanizmasını izleyip kapat.",
    gear: "Cımbız ve tornavida seti",
  },
  {
    id: "kilit",
    name: "Kilit Açmak",
    icon: "lockpick",
    category: "beceri",
    difficulty: 3,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Mekanizmayı anlamak; kendi kapını kilitte bırakmanın da çözümü.",
    firstStep: "Şeffaf pratik kilidinde pimleri tek tek hissetmeye çalış.",
    gear: "Pratik kilidi",
  },
  {
    id: "harita-pusula",
    name: "Harita ve Pusula",
    icon: "navigate",
    category: "beceri",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Telefon kapalıyken yön bulmak; kağıt harita hiç şarj bitirmiyor.",
    firstStep:
      "Haritada bulunduğun yeri işaretle, pusulayla kuzeyi hizala ve rota çiz.",
    gear: "Pusula ve harita",
  },
  {
    id: "kaynak",
    name: "Kaynak Yapmak",
    icon: "weld",
    category: "beceri",
    difficulty: 3,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Metali birleştirmek; tamir yeteneğini tamamen başka seviyeye taşıyor.",
    firstStep: "Hurda iki sacı üst üste koyup düz bir dikiş çekmeyi dene.",
    gear: "Kaynak maskesi ve makine",
  },
  {
    id: "isaret-dili",
    name: "İşaret Dili",
    icon: "sign",
    category: "beceri",
    difficulty: 2,
    minMinutes: 25,
    maxMinutes: 60,
    description:
      "Yeni bir dil ama tamamen elle; alfabesi bir oturuşta öğreniliyor.",
    firstStep: "Parmak alfabesini öğren ve kendi adını akıcı şekilde işaretle.",
  },
  {
    id: "mum",
    name: "Mum Yapımı",
    icon: "candle",
    category: "beceri",
    difficulty: 1,
    minMinutes: 45,
    maxMinutes: 90,
    description:
      "Erit, kokula, dök. Sonucu aynı akşam kullanılabilen kısa bir üretim.",
    firstStep: "Balmumunu erit, fitili ortala ve tek bir bardak mum dök.",
    gear: "Balmumu ve fitil",
  },
  {
    id: "sabun",
    name: "Sabun Yapımı",
    icon: "soap",
    category: "beceri",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 90,
    description: "Ölçü ve güvenlik işi; kimyayı elle görmek de cabası.",
    firstStep: "Hazır sabun bazını erit, koku ve kalıp ekleyip donmaya bırak.",
    gear: "Sabun bazı ve kalıp",
  },
  {
    id: "pasta",
    name: "Pasta Süsleme",
    icon: "cake",
    category: "beceri",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Sıkma torbası kontrolü tamamen tekrar işi; sonucu da paylaşılabiliyor.",
    firstStep:
      "Krema hazırla ve tek bir sıkma ucuyla aynı deseni sıra sıra çalış.",
    gear: "Sıkma torbası",
  },
  {
    id: "asilama",
    name: "Ağaç Aşılama",
    icon: "graft",
    category: "beceri",
    difficulty: 3,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "İki ağacı birleştirmek; sonucu bir yıl sonra meyveyle ölçülüyor.",
    firstStep: "Uygun bir kalem seç, tek bir T aşısı yap ve bantla sar.",
    gear: "Aşı bıçağı ve bant",
  },

  // ── Sosyal ─────────────────────────────────────────────────────────────
  {
    id: "masa-oyunu",
    name: "Masa Oyunu Gecesi",
    icon: "boardgame",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Dört kişi ve tek kutu; telefonlar masadan kalkınca akşam bambaşka geçiyor.",
    firstStep: "Üç kişi çağır, kuralları birlikte oku ve tek parti bitir.",
    gear: "Masa oyunu",
  },
  {
    id: "tavla",
    name: "Tavla",
    icon: "backgammon",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Şans ve olasılık hesabı bir arada; karşı karşıya oturmayı da zorunlu kılıyor.",
    firstStep: "Birini karşına oturt ve beş parti oyna.",
    gear: "Tavla",
  },
  {
    id: "okey",
    name: "Okey",
    icon: "okey",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Dört kişilik klasik; hafıza tutmayı ve olasılık saymayı birlikte çalıştırıyor.",
    firstStep: "Dört kişi toplan ve tek el bitene kadar oyna.",
    gear: "Okey takımı",
  },
  {
    id: "rpg",
    name: "Rol Yapma Oyunu",
    icon: "rpg",
    category: "sosyal",
    difficulty: 2,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Masa başında ortak hikaye kurmak; doğaçlama ve iş birliği aynı anda çalışıyor.",
    firstStep:
      "Kısa bir başlangıç senaryosu seç ve üç kişiyle ilk oturumu oyna.",
  },
  {
    id: "kitap-kulubu",
    name: "Kitap Kulübü",
    icon: "bookclub",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Aynı kitabı okuyup tartışmak, tek başına okumaktan katbekat fazlasını bırakıyor.",
    firstStep:
      "İki kişi bul, ortak bir kitap ve tarih belirle, ilk bölümü tartış.",
  },
  {
    id: "film-kulubu",
    name: "Film Kulübü",
    icon: "filmclub",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 60,
    maxMinutes: 120,
    description: "Birlikte izlemek değil, sonrasında konuşmak asıl iş.",
    firstStep:
      "Bir film seç, izledikten sonra 30 dakika hiç telefon açmadan konuş.",
  },
  {
    id: "dil-degisim",
    name: "Dil Değişimi",
    icon: "exchange",
    category: "sosyal",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 90,
    description:
      "Karşılıklı öğretme: yarım saat onun dili, yarım saat senin dilin.",
    firstStep: "Bir partner bul ve süreyi ikiye bölerek 45 dakika konuş.",
  },
  {
    id: "toplu-yemek",
    name: "Birlikte Yemek",
    icon: "potluck",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 60,
    maxMinutes: 120,
    description: "Herkes bir tabakla gelirse organizasyon yükü de kalmıyor.",
    firstStep:
      "Üç kişiye haber ver, herkes tek yemek getirsin, masayı sen kur.",
  },
  {
    id: "ders-vermek",
    name: "Ders Vermek",
    icon: "mentor",
    category: "sosyal",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Bildiğini birine öğretmek, o konuyu ilk kez gerçekten öğrenmen oluyor.",
    firstStep: "İyi bildiğin bir konuyu birine 45 dakika, örnek çözerek anlat.",
  },
  {
    id: "ziyaret",
    name: "Ziyarete Gitmek",
    icon: "visit",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Yaşlı bir akraba ya da komşu: bir saatlik ziyaretin karşı taraftaki etkisi büyük.",
    firstStep: "Uzun süredir görmediğin birine haber ver ve elin boş gitme.",
  },
  {
    id: "barinak",
    name: "Hayvan Barınağı",
    icon: "shelter",
    category: "sosyal",
    difficulty: 2,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Yürütme, temizlik, mama: barınakların en çok ihtiyaç duyduğu şey insan eli.",
    firstStep:
      "En yakın barınağı ara, hangi gün yardım gerektiğini sor ve git.",
  },
  {
    id: "mahalle",
    name: "Mahalle Temizliği",
    icon: "cleanup",
    category: "sosyal",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Bir saatte gözle görülür fark; yaşadığın sokakla ilişkin de değişiyor.",
    firstStep: "Eldiven ve çuval al, tek bir sokağı baştan sona topla.",
    gear: "Eldiven ve çuval",
  },
  {
    id: "acik-mikrofon",
    name: "Açık Mikrofon",
    icon: "openmic",
    category: "sosyal",
    difficulty: 3,
    minMinutes: 45,
    maxMinutes: 90,
    description:
      "Sahnede beş dakika, sosyal cesareti en hızlı büyüten deneyim.",
    firstStep:
      "Beş dakikalık bir metin hazırla ve açık mikrofon gecesine adını yazdır.",
  },
  {
    id: "koro",
    name: "Koro",
    icon: "choir",
    category: "sosyal",
    difficulty: 2,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Kendi sesini başkalarının içinde duymak; nota okuma da yolda geliyor.",
    firstStep:
      "Yakınındaki bir koroyu bul ve tek provaya misafir olarak katıl.",
  },
  {
    id: "mektup",
    name: "Mektup Yazmak",
    icon: "letter",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 45,
    description:
      "Elle yazılıp postalanan mektup, mesajın asla yapamadığı şeyi yapıyor.",
    firstStep:
      "Bir kişiye bir sayfa mektup yaz, zarfa koy ve gerçekten postala.",
    gear: "Kağıt, zarf, pul",
  },
  {
    id: "aile-arsivi",
    name: "Aile Arşivi",
    icon: "archive",
    category: "sosyal",
    difficulty: 2,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Büyüklerin anlattığı kaydedilmezse kayboluyor; sorular hazırsa akıyor.",
    firstStep:
      "On soru yaz, bir büyüğünü ziyaret et ve anlattıklarını ses kaydına al.",
  },
  {
    id: "misafir",
    name: "Misafir Ağırlamak",
    icon: "host",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 60,
    maxMinutes: 120,
    description:
      "Ev sahipliği bir beceri: menü, zamanlama ve sohbet akışı hep çalışılıyor.",
    firstStep: "İki kişi davet et, tek bir yemek ve tek tatlı planla.",
  },
  {
    id: "bilardo",
    name: "Bilardo / Dart",
    icon: "pub",
    category: "sosyal",
    difficulty: 1,
    minMinutes: 45,
    maxMinutes: 90,
    description:
      "Sıra beklerken konuşulan oyunlar; ikisi de açı ve hedefleme işi.",
    firstStep:
      "Birini çağır, üç parti oyna ve her turda tek şeyi düzeltmeye çalış.",
  },

  // ── Huzur ─────────────────────────────────────────────────────────────
  {
    id: "kutu-nefes",
    name: "Kutu Nefes",
    icon: "boxbreath",
    category: "huzur",
    difficulty: 1,
    minMinutes: 10,
    maxMinutes: 25,
    description:
      "Dörtte al, dörtte tut, dörtte ver. Nabzı dakikalar içinde indiriyor.",
    firstStep:
      "4 saniye al, 4 tut, 4 ver, 4 bekle; bunu 5 dakika kesintisiz sürdür.",
  },
  {
    id: "beden-taramasi",
    name: "Beden Taraması",
    icon: "bodyscan",
    category: "huzur",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 40,
    description:
      "Tepeden tabana dikkat gezdirmek; uykuya geçişi belirgin kolaylaştırıyor.",
    firstStep:
      "Sırt üstü uzan, ayak parmaklarından başına kadar her bölgede 20 saniye kal.",
  },
  {
    id: "tai-chi",
    name: "Tai Chi",
    icon: "taichi",
    category: "huzur",
    difficulty: 2,
    minMinutes: 30,
    maxMinutes: 60,
    description:
      "Yavaş ve kesintisiz hareket; denge ile sakinliği aynı anda çalıştırıyor.",
    firstStep:
      "Tek bir formun ilk üç hareketini çok yavaş, 30 dakika tekrarla.",
  },
  {
    id: "qigong",
    name: "Çi Gong",
    icon: "qigong",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Duruş, nefes ve dikkat üçlüsü; ayakta yapılan sakin bir çalışma.",
    firstStep: "Sekiz temel hareketten ilkini nefesle eşleyerek 20 dakika yap.",
  },
  {
    id: "sicak-dus",
    name: "Sauna / Sıcak Duş",
    icon: "sauna",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Kas gevşemesi ve uyku kalitesi üzerindeki etkisi hemen fark ediliyor.",
    firstStep: "15 dakika sıcakta kal, sonra 5 dakika sessizce oturup soğu.",
  },
  {
    id: "soguk-dus",
    name: "Soğuk Duş",
    icon: "cold",
    category: "huzur",
    difficulty: 2,
    minMinutes: 10,
    maxMinutes: 25,
    description:
      "Rahatsızlığa istekle girmek; sabah uyanıklığını da doğrudan açıyor.",
    firstStep:
      "Duşun sonunda 60 saniye tamamen soğuk suda kal, nefesini yavaş tut.",
  },
  {
    id: "dogada-oturma",
    name: "Doğada Oturmak",
    icon: "sitspot",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 60,
    description:
      "Aynı noktaya her gün oturmak; mevsimin değiştiğini gerçekten görüyorsun.",
    firstStep: "Bir ağacın altına otur, 20 dakika hiç kalkmadan sadece izle.",
  },
  {
    id: "orman",
    name: "Orman Banyosu",
    icon: "forest",
    category: "huzur",
    difficulty: 1,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Hedefsiz orman yürüyüşü; dikkati toplama üzerindeki etkisi ölçülmüş durumda.",
    firstStep:
      "Ormanda telefonsuz yürü, her 10 dakikada durup beş sesi ayırt et.",
  },
  {
    id: "gun-batimi",
    name: "Gün Batımını İzle",
    icon: "sunset",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Yirmi dakika süren, tekrarı olmayan tek gösteri; ücretsiz ve her gün var.",
    firstStep:
      "Batıya bakan bir yer bul, güneş inerken hiçbir şey yapmadan otur.",
  },
  {
    id: "yildiz",
    name: "Yıldız İzlemek",
    icon: "stars",
    category: "huzur",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Şehir dışına yarım saat çıkmak gökyüzünü tamamen değiştiriyor.",
    firstStep:
      "Işıktan uzaklaş, gözün 20 dakika karanlığa alışsın, sonra izle.",
  },
  {
    id: "akvaryum",
    name: "Akvaryum Bakımı",
    icon: "aquarium",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Su değişimi ve bitki bakımı; yavaş geri bildirim veren sakin bir sorumluluk.",
    firstStep: "Suyun dörtte birini değiştir, camı sil ve bitkileri düzelt.",
    gear: "Akvaryum",
  },
  {
    id: "hayvanla",
    name: "Evcil Hayvanla",
    icon: "pet",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 60,
    description:
      "Telefonsuz geçen oyun ve tımar zamanı; iki taraf da sakinleşiyor.",
    firstStep: "20 dakika sadece oyun ve tımar; telefon başka odada kalsın.",
  },
  {
    id: "cay",
    name: "Çay Demlemek",
    icon: "tea",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Demlik, süre, oran: acele edilmediğinde küçük bir tören haline geliyor.",
    firstStep:
      "Tek bir çayı üç farklı demleme süresiyle yap ve tatları karşılaştır.",
  },
  {
    id: "uzun-banyo",
    name: "Uzun Banyo",
    icon: "bath",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Telefon dışarıda kalınca yirmi dakikalık banyo gerçekten dinlendiriyor.",
    firstStep: "Küveti doldur, telefonu başka odada bırak ve 20 dakika kal.",
  },
  {
    id: "foam-roller",
    name: "Foam Roller",
    icon: "roller",
    category: "huzur",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 40,
    description: "Masa başı sırtı ve bacakları açan mekanik bir gevşeme.",
    firstStep: "Sırt, kalça ve baldırda üçer dakika yavaşça yuvarlan.",
    gear: "Foam roller",
  },
  {
    id: "derli-toplu",
    name: "Derli Toplu Etmek",
    icon: "declutter",
    category: "huzur",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 90,
    description:
      "Tek bir çekmeceyi boşaltmak, kafadaki dağınıklığı da azaltıyor.",
    firstStep: "Tek bir çekmeceyi tamamen boşalt, ayır ve geri yerleştir.",
  },
  {
    id: "sukran",
    name: "Şükran Günlüğü",
    icon: "gratitude",
    category: "huzur",
    difficulty: 1,
    minMinutes: 10,
    maxMinutes: 25,
    description:
      "Günün iyi kısmını yazmak; iki hafta sonra bakınca etkisi görünüyor.",
    firstStep:
      "Bugüne dair üç somut şeyi, neden iyi olduklarını da yazarak not et.",
  },
  {
    id: "muze",
    name: "Müze Gezmek",
    icon: "museum",
    category: "huzur",
    difficulty: 1,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Tek bir salonda yavaş dolaşmak, on salonu hızla geçmekten fazlasını bırakıyor.",
    firstStep: "Tek bir salon seç ve üç eserin önünde beşer dakika dur.",
  },
  {
    id: "yalinayak",
    name: "Yalınayak Yürüyüş",
    icon: "barefoot",
    category: "huzur",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 40,
    description:
      "Çimende yalınayak yürümek ayak tabanını ve dengeyi birlikte uyandırıyor.",
    firstStep: "Temiz bir çimenlikte ayakkabısız 15 dakika yavaş yürü.",
  },
  {
    id: "bulut",
    name: "Bulut İzlemek",
    icon: "clouds",
    category: "huzur",
    difficulty: 1,
    minMinutes: 15,
    maxMinutes: 40,
    description: "Hiçbir şey üretmeden bakmak; zihni boşaltmanın en ucuz hali.",
    firstStep: "Sırt üstü uzan ve 15 dakika sadece bulutların hareketini izle.",
  },
  {
    id: "kutuphane",
    name: "Kütüphanede Oturmak",
    icon: "library",
    category: "huzur",
    difficulty: 1,
    minMinutes: 45,
    maxMinutes: 120,
    description:
      "Sessiz ortamın odaklanma üzerindeki etkisi evde taklit edilemiyor.",
    firstStep:
      "En yakın kütüphaneye git ve tek bir işi bitirene kadar orada kal.",
  },
  {
    id: "plak",
    name: "Plak Dinlemek",
    icon: "vinyl",
    category: "huzur",
    difficulty: 1,
    minMinutes: 30,
    maxMinutes: 75,
    description:
      "Atlanamayan albüm: baştan sona dinlemek müziği tekrar bir olay yapıyor.",
    firstStep: "Tek bir albümü hiç durdurmadan, başka iş yapmadan dinle.",
    gear: "Pikap ve plak",
  },
  {
    id: "uyku-rutini",
    name: "Uyku Rutini",
    icon: "sleep",
    category: "huzur",
    difficulty: 1,
    minMinutes: 20,
    maxMinutes: 45,
    description:
      "Yatmadan önceki yarım saati sabitlemek, uykuya geçişi kısaltıyor.",
    firstStep: "Ekranları kapat, ışığı kıs ve 20 dakika sadece kitap oku.",
  },
];

export function getHabit(id: string): Habit | undefined {
  return HABITS.find((h) => h.id === id);
}

export function categoryMeta(id: Category) {
  return CATEGORIES.find((c) => c.id === id) ?? CATEGORIES[0];
}
