import {
  Accessibility,
  Activity,
  Amphora,
  Anchor,
  Anvil,
  Axe,
  Backpack,
  Bandage,
  Bath,
  Bed,
  Bike,
  Binoculars,
  Bird,
  Blocks,
  BookMarked,
  BookOpen,
  Boxes,
  Brain,
  Broom,
  Cake,
  Calculator,
  Camera,
  Cat,
  ChefHat,
  CircleDot,
  CircuitBoard,
  Clapperboard,
  Cloud,
  Clover,
  Club,
  Coffee,
  Cog,
  Compass,
  Component,
  Cpu,
  Croissant,
  Crown,
  CupSoda,
  Dice5,
  Dices,
  Disc2,
  Disc3,
  Droplet,
  Droplets,
  Drum,
  Dumbbell,
  Feather,
  FileText,
  Files,
  Film,
  Fish,
  FishingHook,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Frame,
  Gem,
  Goal,
  Grid2x2,
  Grid3x3,
  Grip,
  Guitar,
  Hammer,
  Hand,
  HandHeart,
  HeartHandshake,
  Hexagon,
  History,
  Home,
  Image,
  Infinity,
  Key,
  Keyboard,
  Lamp,
  Landmark,
  Languages,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Mail,
  Map,
  Martini,
  Megaphone,
  MessageCircle,
  Mic,
  MicVocal,
  Milestone,
  Mountain,
  MountainSnow,
  Move,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Network,
  Newspaper,
  NotebookPen,
  Orbit,
  PaintBucket,
  Paintbrush,
  PawPrint,
  PenLine,
  PenTool,
  PersonStanding,
  Piano,
  Pin,
  Podium,
  Presentation,
  Projector,
  Puzzle,
  Quote,
  Recycle,
  Repeat,
  Ribbon,
  Route,
  Sailboat,
  Scan,
  Scissors,
  Scooter,
  ScrollText,
  Shapes,
  Shield,
  Shirt,
  Shovel,
  ShowerHead,
  Sigma,
  SlidersVertical,
  Smile,
  Soup,
  Spade,
  Sparkles,
  Speech,
  Spool,
  Sprout,
  Stamp,
  Star,
  StickyNote,
  Sun,
  Sunset,
  Sword,
  Swords,
  Target,
  Telescope,
  Tent,
  Terminal,
  Theater,
  Thermometer,
  Timer,
  TreeDeciduous,
  TreePine,
  Trees,
  Trophy,
  Type,
  Users,
  UtensilsCrossed,
  Video,
  Volleyball,
  Watch,
  Waves,
  Waypoints,
  Weight,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Katalogdaki her uğraşın simgesi buradan geçer. Serbest string yerine kayıt
 * defteri: yanlış anahtar derleme zamanında patlar, emoji hiç girmez.
 */
export const HABIT_ICONS = {
  cube: Boxes,
  book: BookOpen,
  guitar: Guitar,
  pen: PenTool,
  terminal: Terminal,
  notebook: NotebookPen,
  run: Footprints,
  dumbbell: Dumbbell,
  stretch: PersonStanding,
  breath: Wind,
  language: Languages,
  chef: ChefHat,
  camera: Camera,
  chess: Crown,
  piano: Piano,
  swim: Waves,
  hike: Mountain,
  origami: Bird,
  mixer: SlidersVertical,
  plant: Sprout,
  calligraphy: Feather,
  coffee: Coffee,
  handshake: HeartHandshake,
  wrench: Wrench,

  // ── Zihin ───────────────────────────────────────────────────────────
  memory: Brain,
  calculator: Calculator,
  sudoku: Grid3x3,
  crossword: LayoutGrid,
  go: Grip,
  cards: Spade,
  keyboard: Keyboard,
  telescope: Telescope,
  binoculars: Binoculars,
  scroll: ScrollText,
  summary: FileText,
  teach: Presentation,
  mindmap: Network,
  history: Landmark,
  map: Map,
  logic: Lightbulb,
  jigsaw: Puzzle,
  recite: Speech,
  sigma: Sigma,
  newspaper: Newspaper,
  checkers: Grid2x2,
  shorthand: PenLine,

  // ── Beden ───────────────────────────────────────────────────────────
  bike: Bike,
  jumprope: Activity,
  calisthenics: Accessibility,
  rowing: Sailboat,
  climb: MountainSnow,
  martial: Swords,
  pingpong: Target,
  ball: Volleyball,
  hoop: Goal,
  pitch: Flag,
  skate: Scooter,
  dance: Music2,
  sprint: Zap,
  stairs: Milestone,
  mobility: Move,
  trek: Route,
  compass: Compass,
  frisbee: Disc2,
  kettlebell: Weight,
  balance: Waypoints,

  // ── Yaratıcı ───────────────────────────────────────────────────────────
  watercolor: Paintbrush,
  acrylic: PaintBucket,
  ceramic: Amphora,
  print: Stamp,
  collage: Scissors,
  zine: Files,
  comic: Frame,
  character: Smile,
  lettering: Type,
  sewing: Spool,
  knitting: Ribbon,
  embroidery: Pin,
  macrame: Shapes,
  jewelry: Gem,
  carving: Axe,
  model: Blocks,
  stopmotion: Clapperboard,
  shortfilm: Video,
  poem: Quote,
  story: StickyNote,
  screenplay: Film,
  lyrics: Music,
  drum: Drum,
  ukulele: Music3,
  violin: Music4,
  vocal: MicVocal,
  improv: Theater,
  voiceover: Mic,
  ebru: Droplet,
  bonsai: TreePine,

  // ── Beceri ───────────────────────────────────────────────────────────
  carpentry: Hammer,
  solder: CircuitBoard,
  arduino: Cpu,
  printer3d: Layers,
  pcbuild: Component,
  bikefix: Cog,
  knots: Anchor,
  camp: Tent,
  fire: Flame,
  firstaid: Bandage,
  espresso: CupSoda,
  cocktail: Martini,
  bread: Croissant,
  ferment: Soup,
  fishing: FishingHook,
  foraging: Leaf,
  sharpen: Sword,
  juggle: Orbit,
  cardtrick: Club,
  machine: Shirt,
  leather: Backpack,
  watchfix: Watch,
  lockpick: Key,
  navigate: Navigation,
  weld: Anvil,
  sign: Hand,
  candle: Lamp,
  soap: Droplets,
  cake: Cake,
  graft: Shovel,

  // ── Sosyal ───────────────────────────────────────────────────────────
  boardgame: Dices,
  backgammon: Dice5,
  okey: Hexagon,
  rpg: Shield,
  bookclub: Library,
  filmclub: Projector,
  exchange: MessageCircle,
  potluck: UtensilsCrossed,
  mentor: Podium,
  visit: HandHeart,
  shelter: PawPrint,
  cleanup: Recycle,
  openmic: Megaphone,
  choir: Users,
  letter: Mail,
  archive: History,
  host: Home,
  pub: Trophy,

  // ── Huzur ───────────────────────────────────────────────────────────
  boxbreath: Timer,
  bodyscan: Scan,
  taichi: Infinity,
  qigong: Sun,
  sauna: Thermometer,
  cold: ShowerHead,
  sitspot: TreeDeciduous,
  forest: Trees,
  sunset: Sunset,
  stars: Star,
  aquarium: Fish,
  pet: Cat,
  tea: Flower2,
  bath: Bath,
  roller: Repeat,
  declutter: Broom,
  gratitude: Sparkles,
  museum: Image,
  barefoot: Clover,
  clouds: Cloud,
  library: BookMarked,
  vinyl: Disc3,
  sleep: Bed,
} as const satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof HABIT_ICONS;

/** Geçmiş kayıtlar bilinmeyen bir anahtar taşıyabilir; arayüz boş kalmasın. */
export function iconFor(key: string): LucideIcon {
  return HABIT_ICONS[key as IconKey] ?? CircleDot;
}

/**
 * Eski sürüm oturumları emoji saklıyordu. Kayıt silinmesin diye okurken
 * anahtara çevriliyor.
 */
const LEGACY_EMOJI_TO_ICON: Record<string, IconKey> = {
  "🧩": "cube",
  "📚": "book",
  "🎸": "guitar",
  "✏️": "pen",
  "💻": "terminal",
  "📝": "notebook",
  "🏃": "run",
  "🏋️": "dumbbell",
  "🧘": "stretch",
  "🌬️": "breath",
  "🗣️": "language",
  "🍳": "chef",
  "📷": "camera",
  "♟️": "chess",
  "🎹": "piano",
  "🏊": "swim",
  "🚶": "hike",
  "🦢": "origami",
  "🎛️": "mixer",
  "🪴": "plant",
  "🖋️": "calligraphy",
  "☕": "coffee",
  "🤝": "handshake",
  "🔧": "wrench",
};

export function iconKeyFromEmoji(emoji: string | undefined): IconKey | undefined {
  return emoji ? LEGACY_EMOJI_TO_ICON[emoji] : undefined;
}
